# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core
BLOCKSDSEXT	?= /opt/blocksds/external

# The ARM7 has to be built against the same copy of the library as the ARM9,
# because both of them share the structures that it uses to talk between the two
# CPUs. See Makefile.arm9.
DSWIFI_DL	?= $(abspath $(CURDIR)/../..)

ifeq ($(DEBUG),1)
    DEFINES	:= -DDSWIFI_LOGS
    LIBS	:= -ldswifi_dl7d -lnds7d
else
    LIBS	:= -ldswifi_dl7 -lnds7
endif

LIBDIRS		:= $(DSWIFI_DL)

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm7
